---
- name: Using role to set analytics settings
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: https://controller.node
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false
    controller_settings:
      settings:
        INSIGHTS_TRACKING_STATE: true
        REDHAT_USERNAME: email@email.com
        REDHAT_PASSWORD: nothing
        AUTOMATION_ANALYTICS_GATHER_INTERVAL: 14400
  collections:
    - ansible.controller
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.settings
...
