---
- name: Playbook to add subscription manifest to controller
  hosts: localhost
  connection: local
  vars:
    controller_hostname: https://controller.node
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false
    controller_license:
      manifest_file: manifest_file.zip
      force: true
  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.license
...
