---
- name: Using role to create project
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: https://controller.node
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false
    controller_projects:
      - name: Test Project
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git
        scm_branch: master
        scm_clean: true
        description: Test Project 1
        organization: Default
        wait: true
        update_project: true
  collections:
    - ansible.controller
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.projects
...
