---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  environment:
     CONTROLLER_HOST: https://controller.node
     CONTROLLER_USERNAME: admin
     CONTROLLER_PASSWORD: secret123
     CONTROLLER_VERIFY_SSL: False

  tasks:
    - name: Export workflow job template
      ansible.controller.export:
        workflow_job_templates: Complicated workflow schema
      register: export_results

    - debug:
        var: export_results

    - name: Export workflow job template to file
      copy:
        content: "{{ export_results | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: workflow.yaml
...
